#Step 1: Build React App
FROM node:20.16-alpine3.18 as build

# Set the working directory inside the container
WORKDIR /app 
# Copy package.json and install dependencies
COPY package.json .
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build