name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t thenikhilseth/voice-control-data-fetching -f C:\Users\nikhi\Projects\Voice-Assist Data Fetching\Dockerfile
      - name: Publish image to docker hub
        run: docker push thenikhilseth/voice-control-data-fetching:latest   

  deploy: 
    needs: build
    runs-on: aws-ec2
    steps:
        - name: Pull image from docker hub
          run: docker pull thenikhilseth/voice-control-data-fetching:latest 
        - name: Delete Old Container
          run: docker rm -f reactContainer
        - name: Run docker container
          run: docker run -d -p 3000:80 --name reactContainer thenikhilseth/voice-control-data-fetching   